import type { Metadata } from "next";
import cn from 'classnames'
import "./globals.css";
import "@/styles/index.scss";
import { Epilogue, Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
  weight: ["400", "500", "700"],
  variable: "--font-grotesk",
});

const epilogue = Epilogue({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={cn(spaceGrotesk.variable, epilogue.className, "h-full")}>
      <body>{children}</body>
    </html>
  );
}
